"use client";
/**
 * Loads a season's simulation artifact and the Sleeper-id -> dense-index map.
 *
 * The artifact is ~250 KB of JSON generated by scripts/build_web_artifact.py. Player ids
 * are interned to dense integers there because the engine works over typed arrays; the map
 * this hook builds is the only place Sleeper's string ids are translated.
 */
import * as React from "react";
import { Artifact } from "@/services/sim/engine";

export type SimArtifactState = {
  artifact: Artifact | null;
  /** Sleeper player_id -> dense index into artifact.players.* */
  idx: Map<string, number> | null;
  error: string | null;
  loading: boolean;
};

export function useSimArtifact(season: string): SimArtifactState {
  const [artifact, setArtifact] = React.useState<Artifact | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    setArtifact(null);
    fetch(`/sim/season-${season}.json`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((a: Artifact) => { if (!cancelled) { setArtifact(a); setLoading(false); } })
      .catch((e: Error) => { if (!cancelled) { setError(e.message); setLoading(false); } });
    return () => { cancelled = true; };
  }, [season]);

  const idx = React.useMemo(() => {
    if (!artifact) return null;
    const m = new Map<string, number>();
    artifact.players.sleeperId.forEach((sid, i) => m.set(sid, i));
    return m;
  }, [artifact]);

  return { artifact, idx, error, loading };
}

/**
 * Which seat is mine, from the picks that have ACTUALLY happened.
 *
 * `draft.draft_order` is not trustworthy for this: in a live 16-team draft it reported
 * slot 1 for a user whose real picks were #6/#27/#43, i.e. slot 6. It is used only as a
 * fallback before any pick exists, when there is nothing better.
 */
export function inferSeat(
  teams: number,
  picks: { pick_no: number; round: number; picked_by: string }[],
  currentUserId?: string,
  draftOrder?: Record<string, number> | null,
  reversalRound = 0,
): number {
  if (!currentUserId) return -1;
  const mine = picks.filter((p) => p.picked_by === currentUserId);
  if (mine.length) {
    const p = mine[0];
    let seat = (p.pick_no - 1) % teams;
    let fwd = p.round % 2 === 1;
    if (reversalRound && p.round >= reversalRound) fwd = !fwd;
    if (!fwd) seat = teams - 1 - seat;
    return seat;
  }
  if (draftOrder && currentUserId in draftOrder) {
    const slot = draftOrder[currentUserId];
    if (slot >= 1 && slot <= teams) return slot - 1;
  }
  return -1;
}

/**
 * denseIndex -> rank, from the user's selected ranking set.
 *
 * Both the per-manager and per-player views need this and must agree, otherwise one would
 * simulate opponents drafting the user's board while the other had them following market
 * ADP -- and the availability numbers would then describe a different draft from the odds.
 * Returns null when too few rows match to be a usable board.
 */
export function buildRankOverride(
  players: { player_id: string }[],
  idx: Map<string, number> | null,
  size: number,
  minMatched = 50,
): Int32Array | null {
  if (!idx || !players.length) return null;
  const a = new Int32Array(size);
  let r = 0;
  for (const p of players) {
    const i = idx.get(p.player_id);
    if (i === undefined) continue;
    a[i] = ++r;
  }
  return r >= minMatched ? a : null;
}
