"""
Script to generate dynasty rankings.

Sleeper's ADP/projections (used for the redraft rankings.json) aren't dynasty-aware
-- they don't account for player age or draft capital, which dominate dynasty trade
value. FantasyCalc publishes a free, unauthenticated API of crowd-sourced dynasty
trade values (the same endpoint their own site's rankings page uses) that already
includes each player's Sleeper player_id, so no name-matching is needed.

FantasyCalc doesn't value K/DEF (no dynasty trade value), so those are carried over
from the redraft rankings.json, which is generated by generate_rankings.py.
"""

import json
import math
import os
import requests

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data')
REDRAFT_RANKINGS_FILE = os.path.join(DATA_DIR, 'rankings.json')
OUTPUT_FILE = os.path.join(DATA_DIR, 'dynasty_rankings.json')
FANTASYCALC_URL = "https://api.fantasycalc.com/values/current?isDynasty=true&numQbs=1&numTeams=12&ppr=1"


def fetch_dynasty_values():
    print(f"Fetching dynasty values from {FANTASYCALC_URL}...")
    resp = requests.get(FANTASYCALC_URL, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    print(f"Fetched {len(data)} entries.")
    return data


def generate_dynasty_rankings():
    raw = fetch_dynasty_values()

    players = []
    for entry in raw:
        p = entry.get('player', {})
        if p.get('position') == 'PICK':
            continue
        sleeper_id = p.get('sleeperId')
        if not sleeper_id:
            continue
        players.append({
            'player_id': sleeper_id,
            'name': p.get('name'),
            'position': p.get('position'),
            'team': p.get('maybeTeam') or 'FA',
            'dynasty_value': entry.get('value') or 0,
        })

    players.sort(key=lambda x: -x['dynasty_value'])

    final_rankings = []
    for i, p in enumerate(players):
        rank = i + 1
        final_rankings.append({
            'player_id': p['player_id'],
            'name': p['name'],
            'position': p['position'],
            'team': p['team'],
            'rank': rank,
            'tier': math.ceil(rank / 12),
        })

    try:
        with open(REDRAFT_RANKINGS_FILE, 'r') as f:
            redraft = json.load(f)
        kickers_and_def = [p for p in redraft if p['position'] in ('K', 'DEF')]
        next_rank = len(final_rankings) + 1
        for i, p in enumerate(kickers_and_def):
            rank = next_rank + i
            final_rankings.append({
                'player_id': p['player_id'],
                'name': p['name'],
                'position': p['position'],
                'team': p['team'],
                'rank': rank,
                'tier': math.ceil(rank / 12),
                'projected_points': p.get('projected_points'),
            })
        print(f"Carried over {len(kickers_and_def)} K/DEF entries from redraft rankings.")
    except FileNotFoundError:
        print(f"Warning: {REDRAFT_RANKINGS_FILE} not found, skipping K/DEF merge.")

    print(f"Generated dynasty rankings for {len(final_rankings)} players.")

    with open(OUTPUT_FILE, 'w') as f:
        json.dump(final_rankings, f, indent=2)
    print(f"Saved to {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_dynasty_rankings()
